# Site settings
title: Algoritics
email: alexander.cabello@algoritics.com
url: https://info.algoritics.com
description: "Algoritics"
skills: "Software Development • Machine Learning • Simulation"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 448aff #80B3FF
  primary-rgb: "68,138,255" #"128,179,255"
  secondary: 666666 #FD6E8A
  secondary-dark: 444 #A2122F
  light: f6f6f6

# Footer settings
footer:
  copyright: Algoritics
  location: Location
  social: Social Media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/mixxen
  - title: facebook
    url: http://facebook.com/algoritics
  - title: github
    url: http://github.com/mixxen

# Postal address (add as many lines as necessary)
address:
  - line: Maui
  - line: Kahului, HI 96732

# Credits content
credits: 'Design by <a href="https://www.linkedin.com/in/alexcabello">Alex Cabello</a>'

# Build settings
markdown: kramdown
permalink: pretty
